name: Publish preview

permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  publish-preview:
    runs-on: ubuntu-latest

    steps:

    - name: Check out repository
      uses: actions/checkout@v3

    - name: Prepare Node.js
      uses: actions/setup-node@v3.6.0
      with:
        node-version: '16'
    
    - name: Restore cache of NPM packages
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Fetch NPM packages
      run: |
        npm i
      
    - name: Prepare distribution-ready files
      run: |
        npm run update-reveal
        npm run build

    - name: Copy distribution files into preview folder
      run: |
        cp -Rv build/* preview/

    - name: Deploy preview slide deck
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: preview/
        branch: gh-pages
      if: github.ref == 'refs/heads/main'
